version: 1
disable_existing_loggers: true

formatters:
    standard:
        format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: standard
        stream: ext://sys.stdout

    file_handler:
        class: logging.handlers.RotatingFileHandler
        level: DEBUG
        formatter: standard
        filename: ./trackerstats.log
        maxBytes: 10485760 # 10MB
        backupCount: 10
        encoding: utf8

root:
    level: NOTSET
    handlers: [console, file_handler]

loggers:
    <module>:
        level: INFO
        handlers: [console, file_handler]

    <module.x>:
        level: DEBUG
        handlers: [console, file_handler]